
import React from 'react';
import { AiAnalysisResult, AiIssue } from '../types';
import { Brain, CheckCircle, CheckSquare, AlertCircle } from 'lucide-react';

interface AiReportProps {
  aiResult: AiAnalysisResult | null;
  loading: boolean;
  onRequest: () => void;
}

const AiReport: React.FC<AiReportProps> = ({ aiResult, loading, onRequest }) => {
  return (
    <div className={`
        rounded-xl border relative overflow-hidden flex flex-col transition-all duration-500 h-full min-h-[500px]
        ${!aiResult && !loading 
            ? 'bg-gradient-to-b from-red-950 via-black to-red-950 border-red-900 shadow-[0_0_30px_-10px_rgba(220,38,38,0.5)]' 
            : 'bg-[#121212] border-[#222]' 
        }
    `}>
      
      {/* Initial State View */}
      {!aiResult && !loading && (
        <div className="flex flex-col h-full">
            <div className="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-red-500 to-transparent opacity-70"></div>
            <div className="absolute bottom-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-red-900 to-transparent opacity-50"></div>
            
            <div className="p-6 md:p-8 flex-1 flex flex-col justify-center items-center relative z-10">
                <div className="absolute inset-0 bg-gradient-to-b from-red-900/10 to-transparent pointer-events-none"></div>

                <div className="flex flex-col sm:flex-row items-center sm:items-start gap-4 mb-8 w-full justify-start text-center sm:text-left">
                    <div className="bg-gradient-to-br from-red-900 to-red-950 p-3 rounded-xl border border-red-500/30 shadow-lg shadow-red-900/20">
                        <Brain className="text-red-400 drop-shadow-[0_0_8px_rgba(248,113,113,0.5)]" size={32} />
                    </div>
                    <div>
                        <h3 className="font-bold text-white text-xl tracking-tight drop-shadow-md">Deep SEO Audit</h3>
                        <p className="text-[10px] text-red-300/70 font-medium uppercase tracking-wider mt-1">SEO & GEO Intelligence</p>
                    </div>
                </div>

                <div className="flex-1 flex flex-col justify-center w-full">
                    <p className="text-gray-300 text-sm mb-8 md:mb-10 leading-relaxed text-center px-2 font-light">
                        Identify and address all SEO and geo-targeting issues to rank at the top for standard and generative search.
                    </p>

                    <button 
                        onClick={onRequest}
                        className="w-full py-3 md:py-4 px-6 bg-gradient-to-b from-[#dc2626] to-[#991b1b] hover:from-[#ef4444] hover:to-[#b91c1c] text-white rounded-lg font-bold text-sm md:text-base transition-all shadow-[0_4px_20px_-5px_rgba(220,38,38,0.5)] hover:shadow-[0_6px_25px_-5px_rgba(220,38,38,0.7)] flex items-center justify-center gap-3 group border-t border-red-400/20"
                    >
                        <Brain size={18} className="text-white" />
                        Start Comprehensive Audit
                    </button>
                </div>
            </div>
        </div>
      )}

      {/* Loading State */}
      {loading && (
        <div className="flex-1 flex flex-col items-center justify-center py-10 space-y-4 relative min-h-[500px]">
            <div className="absolute inset-0 bg-black/50 z-0"></div>
            <div className="relative z-10">
                <div className="animate-spin rounded-full h-10 w-10 md:h-12 md:w-12 border-b-2 border-red-500"></div>
            </div>
            <p className="text-sm text-red-400 animate-pulse relative z-10 font-medium">Analyzing content strategy & tech stack...</p>
        </div>
      )}

      {/* Results State */}
      {aiResult && (
        <div className="p-4 flex-1 flex flex-col h-full max-h-[1200px]">
            <div className="flex items-center gap-3 mb-4 shrink-0">
                <div className="bg-brand-900/20 p-2 rounded-lg border border-brand-500/20">
                    <Brain className="text-brand-400" size={20} />
                </div>
                <div>
                    <h3 className="font-bold text-white text-base md:text-lg leading-tight">Audit Report</h3>
                    <p className="text-[10px] text-brand-300">Generated by Gemini</p>
                </div>
            </div>
            
            <div className="space-y-4 animate-fade-in overflow-y-auto custom-scrollbar flex-1 pr-1">
                
                {/* Checklist Summary */}
                {aiResult.checklist && aiResult.checklist.length > 0 && (
                    <div className="bg-[#0a0a0a] rounded-lg border border-[#333] p-3">
                        <h4 className="flex items-center gap-2 text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2">
                            <CheckSquare size={12} className="text-green-500"/> Assessment Checklist
                        </h4>
                        <ul className="space-y-1.5">
                            {aiResult.checklist.map((step, i) => (
                                <li key={i} className="text-[10px] md:text-xs text-gray-300 flex items-start gap-2">
                                    <CheckCircle size={12} className="text-green-500 mt-0.5 shrink-0" />
                                    <span>{step}</span>
                                </li>
                            ))}
                        </ul>
                    </div>
                )}

                {/* Issues List */}
                <div className="space-y-3">
                    {aiResult.issues && aiResult.issues.length > 0 ? (
                        aiResult.issues.map((issue, idx) => (
                            <div key={idx} className="bg-[#0a0a0a] rounded-lg border border-[#222] hover:border-red-900/50 transition-colors p-3 group relative overflow-hidden">
                                 <div className={`absolute left-0 top-0 bottom-0 w-1 ${
                                     issue.impact === 'High' ? 'bg-red-600' : issue.impact === 'Medium' ? 'bg-orange-500' : 'bg-gray-500'
                                 }`}></div>
                                 
                                 <div className="pl-2">
                                     <div className="flex justify-between items-start mb-1">
                                         <div className="flex items-center gap-2">
                                             <span className={`text-[9px] uppercase font-bold px-1.5 py-0.5 rounded border ${
                                                 issue.impact === 'High' ? 'bg-red-900/20 text-red-400 border-red-900/30' : 
                                                 issue.impact === 'Medium' ? 'bg-orange-900/20 text-orange-400 border-orange-900/30' : 'bg-gray-800 text-gray-400 border-gray-700'
                                             }`}>
                                                 {issue.impact}
                                             </span>
                                             <span className="text-[9px] text-gray-500 bg-[#1a1a1a] px-1.5 py-0.5 rounded">{issue.category}</span>
                                         </div>
                                     </div>
                                     
                                     <h4 className="text-white font-bold text-xs md:text-sm mb-1 leading-tight">{issue.issue_description}</h4>
                                     
                                     <div className="text-[10px] text-gray-400 mb-2 font-mono bg-[#111] px-1.5 py-0.5 rounded inline-block truncate max-w-full">
                                        {issue.page_or_section}
                                     </div>

                                     <p className="text-[10px] md:text-xs text-gray-300 leading-relaxed border-t border-[#222] pt-2 mt-1">
                                        <span className="text-brand-400 font-semibold">Fix:</span> {issue.recommendation}
                                     </p>

                                     {issue.error_or_notes && (
                                         <div className="mt-2 flex items-start gap-1.5 bg-red-950/20 p-1.5 rounded border border-red-900/20">
                                             <AlertCircle size={10} className="text-red-400 mt-0.5 shrink-0" />
                                             <p className="text-[9px] text-red-300 italic">{issue.error_or_notes}</p>
                                         </div>
                                     )}
                                 </div>
                            </div>
                        ))
                    ) : (
                        <div className="text-center py-8 text-gray-500 text-xs">
                            No critical issues found.
                        </div>
                    )}
                </div>
            </div>
        </div>
      )}
    </div>
  );
};

export default AiReport;
